sudo: true
services:
 - docker
before_install:
  - docker pull icambron/luxon
  - ./docker/npm install
script:
  - ./docker/npm run build
  - ./docker/npm run format-check
  - ./docker/npm run test
  - ./docker/npm run site
  - bash <(curl -s https://codecov.io/bash)

