version: 2

jobs:
  setup:
    docker:
      - image: circleci/node:8.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Install ICU
          command: npm install full-icu
      - run:
          name: Install Gulp
          command: npm install gulp-cli
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
      - run:
          name: Lint
          command: ./node_modules/gulp-cli/bin/gulp.js lint
      - run:
          name: Build
          command: ./node_modules/gulp-cli/bin/gulp.js build

  utc:
    docker:
      - image: circleci/node:8.8.1
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Test in UTC
          command: NODE_ICU_DATA="$(pwd)/node_modules/full-icu" ./node_modules/gulp-cli/bin/gulp.js ci

  ny:
    docker:
      - image: circleci/node:8.8.1
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Test in America/New_York
          command: NODE_ICU_DATA="$(pwd)/node_modules/full-icu" CODE_COVERAGE=yes TZ=America/New_York ./node_modules/gulp-cli/bin/gulp.js test
      - run:
          name: Upload coveralls
          command: ./node_modules/gulp-cli/bin/gulp.js coveralls

  docs:
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Build docs
          command: ./node_modules/gulp-cli/bin/gulp.js docs

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - utc:
          requires:
            - setup
      - ny:
          requires:
            - setup
      - docs:
          requires:
            - setup
